[WORKING] /nix, luks keyfile, 100% ni bootstrap, split common/gui apps, by id
* Separate partition for /nix store
* Option to use a keyfile instead of passphrase for LUKS (for e.g. Minoo)
* 100% non-interactive bootstrap process
* Split up common and common gui apps (again for Minoo which is cmdline only)
* Use by-id for main drive as it's more stable than by-uuid

diff --git a/sync-and-remove b/sync-and-remove
--- a/sync-and-remove
+++ b/sync-and-remove
@@ -1,1 +1,21 @@
-rsync -r --exclude=result . /run/media/phil/nixos-data/nixos-files && umount /run/media/phil/nixos-data
+#!/usr/bin/env sh
+
+unmount=1
+
+while getopts 'u' OPTION; do
+  case "$OPTION" in
+    u)
+      unmount=0
+      ;;
+  esac
+done
+
+if [ ! -d /run/media/phil/nixos-data ]; then
+  echo "ERROR: Can't find nixos-data USB stick. Aborting."
+  exit 1
+fi
+
+mkdir -p /run/media/phil/nixos-data/nixos-files
+cp /data/sync/HomeDatabase.kdbx /run/media/phil/nixos-data/
+rsync -a --exclude=result . /run/media/phil/nixos-data/nixos-files
+[ "$unmount" -eq "1" ] && umount /run/media/phil/nixos-data
